// Generated by CoffeeScript 1.10.0
(function() {
  var DefaultInOutComponent, ExtendedComponent,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ExtendedComponent = require('./ExtendedComponent.coffee');

  DefaultInOutComponent = (function(superClass) {
    extend(DefaultInOutComponent, superClass);

    function DefaultInOutComponent() {
      this.inPorts = new noflo.InPorts({
        "in": {
          datatype: this.inType || 'any',
          description: this.inDesc || 'default in port'
        }
      });
      this.outPorts = new noflo.OutPorts({
        out: {
          datatype: this.inType || 'any',
          description: this.outDesc || 'default out port'
        },
        error: {
          datatype: 'object'
        }
      });
    }

    return DefaultInOutComponent;

  })(ExtendedComponent);

  module.exports.DefaultInOutComponent = DefaultInOutComponent;

}).call(this);
