language: node_js
node_js:
- '4.1'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install -g grunt-cli
script: npm test
after_success:
- grunt gh-pages
addons:
  postgresql: "9.4"

services:
  - postgresql
