language: node_js
node_js:
  - "5.1.0"
  - "4.2"
  - "4.1"
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install -g grunt-cli
script: npm test
after_success:
  - grunt gh-pages
